// SPDX-FileCopyrightText: © 2022 woifes <https://github.com/woifes>
// SPDX-License-Identifier: UNLICENSED

import { UNSUBSCRIBE_HOOK_NAME } from "./constants";

/**
 * The method decorated will trigger an unsubscribe of all subscribes which are generated by other decorates (not your own ones)
 */
export function MqttUnsubHook() {
    return function (
        target: any,
        propertyKey: string | symbol,
        descriptor: PropertyDescriptor
    ) {
        if (typeof propertyKey == "string") {
            if (descriptor.value != undefined) {
                //Method
                target[UNSUBSCRIBE_HOOK_NAME] = propertyKey;
            } else {
                throw new Error(
                    `MqttConnectHandler set on something wich is not a method`
                );
            }
        } else {
            throw new Error(`MqttUnsubHook can not be set on Symbol property`);
        }
    };
}
