name: client01
mqtt:
  url: localhost
  clientId: client01
yasdi:
  sendDelayS: 5
  mqttPrefix: tags
  plants:
    - name: plant01
      alias: roof01
      inverter:
        - id: inv01
          serialNumber: 123456
          pNomW: 1500
          suntraceInfo:
            coordinates:
              latitude: 1
              longitude: 2
              heightAboveSeeLevelKM: 3
            orientation:
              directionDeg: 1
              tiltDeg: 2
        - id: inv02
          serialNumber: 789
  suntraceInfo:
    coordinates:
      latitude: 1
      longitude: 2
      heightAboveSeeLevelKM: 3
    orientation:
      directionDeg: 1
      tiltDeg: 2